### PR TITLE
* Version upgrades for dependency libraries : clojurescript: 1.7.145 …

### PR DESCRIPTION
**Pull request by tokomakoma123**
@plexus Please accept my pull request if my enhancements are all right.

…=> 1.7.189, om: 1.0.0-alpha15 => 1.0.0-alpha28, figwheel => 0.4.1, figwheel-sidecar 0.4.1 => 0.5.0-2, lein-figwheel 0.4.1 =>  0.5.0-2

### CODE REVIEW

**Comment by plexus** [comment]
thanks, released as 0.8.2-SNAPSHOT

**Comment by tokomakoma123** [comment]
It's my pleasure.

**Comment by psalaberria002** [comment]
Is this working? I have tried creating a new project based on 0.8.2-SNAPSHOT, but the files do not reload automatically in the browser. 

``$ lein new chestnut test --snapshot
``

First I got an error in dev.clj, which complained about [clojurescript-build.auto :as auto]. After I've removed this, the project builds, but the autoreloading does not work.

What am I missing?

Thank you in advance.

**Comment by plexus** [comment]
Not sure, if you want a stable known good version then stick to 0.8.1. Upgrading dependencies almost always breaks things for Chestnut so we'll have to work through that.

I'm starting work on 0.9.0, which will see some big changes, but will also be well tested when it's released.

**Comment by psalaberria002** [comment]
Thank you for the fast reply. I am currently trying to update the development dependencies, and this commit looked promising. I will have to dig more into it.

**Comment by tokomakoma123** [comment]
I've tested using cider and it didn't show any error and weasel was working. Using bare 'lein repl' and (run) caused an error.  I mainly use the weasel feature and I didn't notice that (I should have tested it !)

I've eliminated [clojurescript-build.auto :as auto] and replaced dev/start-figwheel as follows:

```clj
(defn start-figwheel []
  (ra/start-figwheel!
   {
    ;;:figwheel-options {} ;; <-- figwheel server config goes here 
    :build-ids ["dev"]   ;; <-- a vector of build ids to start autobuilding
    :css-dirs ["resources/public/css"] 
     :all-builds          ;; <-- supply your build configs here
     [{:id "dev"
       :figwheel true
       :source-paths ["src/cljs" "env/dev/cljs" "/home/makoto/clojure/my-cljs-examples/src/cljs"]
       :compiler {
                  ;;:main "myapp3.core"
                  :output-to            "resources/public/js/app.js"
                  :output-dir           "/home/makoto/clojure/my-cljs-examples/resources/public/js/out"
                  :asset-path            "out"
                  :source-map           true
                  :optimizations        :none
                  :source-map-timestamp true
                  :verbose true
                  :preamble             ["react/react.min.js"]
                  }
       }]}
   ))
```
It seemed detect a modification of file but it didn't update the contents of browser.
I am trying to fix this problem. Sorry for inconvenience.

**Pull request merged**
