### PR TITLE
List some other templates

### PR DESCRIPTION
**Pull request by deg**
If you are amenable to listing the "competition", I've added links to a few similar templates.

### CODE REVIEW

**Comment by featheredtoast** [comment]
I'd be open to it, as long as we're comparing apples to apples. Maybe we can list these out as alternatives, rather than "other", along with a one liner about its focus and how it differs?

It doesn't have to be this specific, but something like Bidi's comparion chart could be helpful for new users - https://github.com/juxt/bidi

That'd be my suggestion, I can't speak on behalf of @plexus

**Comment by plexus** [comment]
I find this difficult, as it implies some level of endorsement, and I haven't been able to look at most of these, and if I did, not in detail. I also don't see much value in just a list of links, without any explanation about what they do or why they are different.

It's also yet another thing that will go stale over time and so brings extra maintenance work.

If someone would start and maintain a curated list of templates, with some explanation of what they do, then I'd be happy to link to it.

**Comment by deg** [comment]
Understood and I’m coming to agree with you. My idea of maintaining the list of every project in each other one was bad, since it requires so many updates and perceived endorsements.

Would you be willing to keep just the link from the last line of my patch?  It’s a link to https://goo.gl/ZZH8fm, which I am maintaining as curated list of templates.

**Comment by plexus** [comment]
Yes, that'd be cool! (not only because chestnut is listed first ;))

**Comment by deg** [comment]
Great. I've modified the PR.  I tried to match the wording to my sense of what you'd want to say, but I'm obviously just guessing. I'm 100% cool with any wording you choose.

**Comment by plexus** [comment]
That seems fine. You do have a typo: "differentperspective"

**Comment by deg** [comment]
Oops, sorry. Can you fix it or do you need me to? I can't right now.

Sent from my phone, +972 54 723-0120
Please excuse my auto-correct eras.




On Fri, Aug 18, 2017 at 3:37 PM +0300, "Arne Brasseur" <notifications@github.com<mailto:notifications@github.com>> wrote:

That seems fine. You do have a typo: "differentperspective"

**Comment by plexus** [comment]
Thanks a lot!

**Pull request merged**
