### PR TITLE
Updated several dependencies

### PR DESCRIPTION
**Pull request by casidiablo**
Bump!

- `org.clojure/clojurescript 0.0-2511` to `0.0-2665`
- `lein-cljsbuild 1.0.3` to `1.0.5`
- `figwheel* 0.2.1-SNAPSHOT` to `0.2.5-SNAPSHOT`
- `com.cemerick/piggieback 0.1.3` to `0.1.5`
- `weasel 0.4.2` to `0.6.0`
- `compojure 1.3.1` to `1.3.2`

Everything seems to be working fine but more testing is obviously necessary.

### CODE REVIEW

**Comment by plexus** [comment]
Hi @casidiablo, welcome to Chestnut. Thanks for the effort.

Could you target the `upgrade-om` branch instead of `master`? Or drop the upgrade of Clojurescript? We're keeping the version of clojurescript locked for 0.7, see https://github.com/plexus/chestnut/issues/79 . `upgrade-om` is the branch that will become 0.8.

Have you tried running the integration tests? (see the `test` branch)

Cheers,
Arne

**Comment by casidiablo** [comment]
I will PR again against upgrade-om... I think I can't drop the upgrade of clojurescript since weasel and others are using features only available in that newer version.

And I will try to run the integration tests soon.

**Comment by plexus** [comment]
Cool! thanks for the help.

**Comment by plexus** [comment]
Ok so running the tests is actually not trivial, but I've merged them to master and documented in detail how you should be able to get them going

http://plexus.github.io/chestnut/testing.html

**Comment by casidiablo** [comment]
I cloned and `mvn install`ed the jnr projects... and now I'm getting:

```
java.lang.IllegalArgumentException: No matching field found: getPid for class jnr.process.Process
	at clojure.lang.Reflector.getInstanceField(Reflector.java:271)
	at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:315)
	at chestnut.test.integration$test_basic.doInvoke(integration.clj:79)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at chestnut.test.integration$_main.invoke(integration.clj:97)
	at clojure.lang.Var.invoke(Var.java:375)
	at user$eval2746.invoke(NO_SOURCE_FILE:0)
	at clojure.lang.Compiler.eval(Compiler.java:6703)
	at clojure.lang.Compiler.eval(Compiler.java:6693)
	at clojure.lang.Compiler.eval(Compiler.java:6666)
	at clojure.core$eval.invoke(core.clj:2927)
	at leiningen.core.eval$fn__6770.invoke(eval.clj:314)
	at clojure.lang.MultiFn.invoke(MultiFn.java:231)
	at leiningen.core.eval$eval_in_project.invoke(eval.clj:337)
	at leiningen.core.eval$eval_in_project.invoke(eval.clj:344)
```

Am I missing something? Do I have to install an specific version of jnr-*?

**Comment by plexus** [comment]
Sorry about that, I'll look into there. I might have had some local changes that didn't make it upstream.

**Comment by plexus** [comment]
Ok I did actually have some stuff that I didn't make a PR for. I opened two PR's tow jnr-process.

**Pull request closed without merging**
