### PR TITLE
Makes project environ variables available via cljs-env macro 

### PR DESCRIPTION
**Pull request by kevincolyar**
Also stubs out a project config namespace

### CODE REVIEW

**Comment by plexus** [comment]
Hi @kevincolyar. Thank you for this pull request.

Unfortunately I won't merge it as I think this is outside the scope of what Chestnut tries to provide.

I'm still happy to send you some Chestnut stickers if you like, just send me your address.

**Comment by kevincolyar** [comment]
No problem.  I thought it'd be useful to include since it took me forever to find a solution and since Chestnut already has dev and prod configurations by default.

At least others kind find it here in the issues.

I'll email you about the stickers.  Thanks!

**Comment by plexus** [comment]
Also something to note about this approach, it will expend the macro at compile time, so say you build an uberjar then the values of the environment variables on the build machine are now hard coded inside the jar. I'm guessing people might expect env vars from the server to be made available, but that's not the case.

**Comment by kevincolyar** [comment]
Ah, that's good to know.  Not an issue for me personally since I'm not using chestnut's server in production but I could see how that might cause issues.

**Pull request closed without merging**
