### PR TITLE
change versions of clojurescript and om to the latest

### PR DESCRIPTION
**Pull request by tokomakoma123**
I've changed the version of clojurescript from 1.7.122 to 1.7.145 since 1.7.122 does not exists in clojar any more.
I've also changed the version of om to 1.0.0-alpha14.
Please merge my code.

### CODE REVIEW

**Comment by plexus** [comment]
Thanks for the patch! Would you mind adding a changelog entry in the README?

**Comment by tokomakoma123** [comment]
Yes, I will do that.

**Comment by tokomakoma123** [comment]
I've updated other jars to the latest except clojurescript.

* Version upgrades: clojurescript: 1.7.122 => 1.7.145, om: 0.9.0 => 1.0.0-alpha15, tools.nrepl => 0.2.12, figwheel => 0.4.1, figwheel-sidecar => 0.4.1, lein-figwheel => 0.4.1

Updating cljs to the latest(1.7.170) causes an error when running (run) on repl in a chestnut project.

**Comment by plexus** [comment]
Thank you!

Send me your address if you would like some Chestnut stickers in the mail :)

adventure_time_swing

**Comment by mattiasw2** [comment]
I had to roll back this update in my om-bootstrap test project. There were two problems:
1. weasel failed to connect
2. println didn't work
Yes, I agree, a bit strange it had these effects, but now it works as it should.

**Pull request merged**
