### PR TITLE
Prod mode enhancements (incl. updated dependencies to ClojureScript 1.7.48)

### PR DESCRIPTION
**Pull request by slester**
Implements gzip & browser caching as per requested in #118

### CODE REVIEW

**Comment by plexus** [comment]
Looks good to me. Can you update the changelog in the readme as well?

**Comment by slester** [comment]
Sure, for 0.8.2? Or how do you want that structured?

**Comment by plexus** [comment]
Just add a "master" section. I'll fill in the version number when
releasing, that way it's clear these features aren't out yet.

you can add it in the readme, or in the readme and the docs. The latter is
less important though, I generally copy things over from the readme when
releasing.

Next release will likely be 0.9.0 since it's more than just bug fixes.

**Comment by slester** [comment]
@plexus updated README

**Comment by slester** [comment]
Updated again to rewrite the handler to use `->` to allow for easier addition of middleware.

**Comment by slester** [comment]
Updated Clojurescript to 1.7.28, ref #146

**Comment by plexus** [comment]
omgyay

**Pull request merged**
